FROM ubuntu:18.04 as exercise-2-8-frontend 

EXPOSE 5000
WORKDIR /mydir
RUN apt-get update && apt-get install -y wget ca-certificates openssl
RUN apt-get install -y curl telnet 
COPY ./example-frontend .
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash
RUN apt-get install -y nodejs 
WORKDIR /mydir
RUN node -v && npm -v
ENV REACT_APP_BACKEND_URL=http://127.0.0.1:8080
RUN npm install
RUN npm run build
RUN npm install -g serve 

RUN apt-get purge -y --auto-remove curl
RUN rm -rf /var/lib/apt/lists/*

RUN useradd -m appuser
RUN chown appuser .
USER appuser

CMD serve -s -l 5000 build

# docker network create internal-container-network
# docker build -f Dockerfile_frontend -t exercise-2-8-frontend ./
# docker run -d --net=internal-container-network --name exercise-2-8-frontend -p 5000:5000 exercise-2-8-frontend 

