version: '3.8' 

services: 
    exercise2-3-backend:
      image: exercise1_13
      container_name: exercise2-3-backend
      ports:
        - 8080:8080
      environment:
              - PORT=8080
              - REQUEST_ORIGIN=http://127.0.0.1:5000

    exercise2-3-frontend:
      image: exercise1_14_front
      container_name: exercise2-3-frontend
      ports:
        - 5000:5000     
      environment:
              - PORT=5000
              - REACT_APP_BACKEND_URL=http://127.0.0.1:8080 


